--- 
- name: This is Informtaion for Node-1
  hosts: all
  become: true 
  tasks:
    - name: what is gid of local user
      debug:
        msg: "{{ansible_user_gid}}"
    - name: what is ansible_os_family of local user 
      debug:
        msg: "{{ansible_os_family}}"
    - name: what is ansible_machine_id of local user 
      debug:
        msg: "{{ansible_machine_id}}"
...        