--- 
- name: This is Informtaion for Node-1
  hosts: all
  become: true
  tasks: 
    - name: Task 1 - what is gid of local user
      debug:
        msg: "{{ansible_user_gid}}"
    - name: Task 2 - what is ansible_os_family of local user 
      debug:
        msg: "{{ansible_os_family}}"
    - name: Task 3 - what is ansible_machine_id of local user 
      debug:
        msg: "{{ansible_machine_id}}"
    - name: Task 4 - what is ansible_processor of local user 
      debug:
        msg: "{{ansible_processor}}"        
...        