---
- name: new file for prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: "Enter your URL Not needed"
      private : false
  tasks:
  - name: example task
    debug:
      msg: "{{URL}}"