---
- name: this is my shell playbook
  hosts: all
  become: true
  tasks:
    - shell: echo "aaaaaaaaaaaaaaaaaaaa" >> /mnt/sai.txt
    - name: This our first shell task
      debug:
        msg: "{{ansible_distribution}}"
...