---
- name: this is my shell playbook
  hosts: all
  become: true
  tasks:
    - shell: echo "This is online CDEC_DevOps Batch" >> /mnt/analysis.txt
    - name: This our first shell task
      debug:
        msg: "{{ansible_distribution}}"
...