---
- name:
  hosts: all
  become: true
  tasks:
    - name: Print Message one
      debug:
        msg: "{{anisble_user_gid}}"
      tags: tagone
    - name: Print Message two
      debug:
        msg: "{{ansible_env.LOGNAME}}"
      tags: tagtwo
...