--- 
- name: condition 
  hosts: all
  become: true
  tasks:
    - name: print centos
      debug:
        msg: this is centos 
      when: ansible_os_family=="RedHat"
    - name: print ubuntu
      debug:
        msg: this is ubuntu 
      when: ansible_os_family=="Debian"